content/en/projects/shenyu/shenyu-optimize/index.md
content/zh/projects/shenyu/shenyu-optimize/index.md

[doc] modify shenyu optimize

---

content/en/projects/shenyu/spring-cloud-proxy/index.md
content/en/projects/shenyu/thread/index.md
content/en/projects/shenyu/use-data-sync/index.md
content/en/projects/shenyu/waf-plugin/index.md
content/en/projects/shenyu/websocket-plugin/index.md
content/zh/projects/shenyu/spring-cloud-plugin/index.md
content/zh/projects/shenyu/spring-cloud-proxy/index.md
content/zh/projects/shenyu/thread/index.md
content/zh/projects/shenyu/use-data-sync/index.md
content/zh/projects/shenyu/waf-plugin/index.md
content/zh/projects/shenyu/websocket-plugin/index.md

docs: modify shenyu to ShenYu

---

content/en/projects/shenyu/download/index.md
content/zh/projects/shenyu/download/index.md

docs: modify docs of download.md

docs: modify docs of download.md (#21)

---

content/en/projects/shenyu/overview/index.md

Fix some errors on Home page (en)

---

content/en/projects/shenyu/data-sync/index.md
content/zh/projects/shenyu/data-sync/index.md

Delete redundant comments in the display code on data-sync page

---

content/en/projects/shenyu/dictionary-management/index.md
content/zh/projects/shenyu/dictionary-management/index.md

Fix some form errors on dictionary-management page

---

content/en/projects/shenyu/plugin-handle-explanation/index.md
content/zh/projects/shenyu/plugin-handle-explanation/index.md

refer #42 . 
- Only fix form errors.

fix form errors on plugin-handle-explanation page

---

content/en/projects/shenyu/data-sync/index.md
content/zh/projects/shenyu/data-sync/index.md
content/zh/projects/shenyu/download/index.md

change gitee address in  design documents

change gitee address

---

content/zh/community/issue-pr/index.md

translate issue-pr zh_cn page

---

content/en/news/shenyu-2.3.0/index.md
content/zh/news/shenyu-2.3.0/index.md

-  add 2.3.0 news in English  
-  change some spells in 2.3.0 news  in Chinese
-  reformat  2.3.0 news zh markdown

add 2.3.0 news in English

---

content/zh/projects/shenyu/data-sync/index.md

Nacos and Etcd sync doc

---

content/en/projects/shenyu/overview/index.md

Fixes spelling of words

---

content/en/projects/shenyu/jwt-plugin/index.md
content/en/projects/shenyu/oauth2-plugin/index.md
content/en/projects/shenyu/sign-plugin/index.md
content/en/projects/shenyu/waf-plugin/index.md
content/zh/projects/shenyu/sign-plugin/index.md
content/zh/projects/shenyu/waf-plugin/index.md

Updated 'Authority And Certification' doc of en and zh.

Updated 'Authority And Certification' doc

---

content/zh/projects/shenyu/deployment-local/index.md

Update  debug source code  document.

Update  debug source code  document

---

content/en/projects/shenyu/custom-filter/index.md
content/en/projects/shenyu/custom-parsing-ip-and-host/index.md
content/en/projects/shenyu/custom-plugin/index.md
content/en/projects/shenyu/custom-result/index.md
content/en/projects/shenyu/file-and-image/index.md

update English document of Developer Documentation (#141)

---

i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-local.md
versioned_docs/version-2.4.0/deployment/deployment-local.md

I encountered a error when running the code on Windows, and I've included the solution in the document to help people who have the same problem as me.

Add the solution of Git error with file name too long.

---

news/Apache-ShenYu-Committer-2021-09-08.md

Add en committer news.

---

i18n/zh/docusaurus-plugin-content-docs/current/user-guide/admin-usage/authority-management.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/admin-usage/authority-management.md

Update authority-management page

---

i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/developer/custom-plugin.md
versioned_docs/version-2.4.0/developer/custom-plugin.md

update custom plugin handle

---

i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/admin-usage/data-permission.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/admin-usage/role-management.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/admin-usage/data-permission.md
versioned_docs/version-2.4.0/user-guide/admin-usage/data-permission.md
versioned_docs/version-2.4.0/user-guide/admin-usage/role-management.md
versioned_docs/version-2.4.1/user-guide/admin-usage/data-permission.md

Data permissions are provided in version2.4.0 , and now copy the document to the beginning version.

doc copy to early version

---

docs/deployment/deployment-docker.md

modify the docker mount directory problem in window docker

update deployment-docker -v  contents

---

i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-docker.md

modify deployment-docker in chinese Doc of version-2.4.1

modify deployment-docker in chinese Doc of version-2.4.1

---

i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

[fix docs] update docs

---

community/3-contributor.md

[docs] update docs

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

modify error link of code-conduct

<BUG> modify error link of code-conduct

---

community/13-faq.md
i18n/zh/docusaurus-plugin-content-docs-community/current/13-faq.md

About #368 
And I have check my local  effect.

[ISSUE #368] Add FAQ Document in Community

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/13-faq.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

[ISSUE #368] Add FAQ link in contributor

---

docs/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/gateway-property-config.md

[DOC] Add netty tcp config for gateway property config

---

community/5-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/5-release-guide.md

delete
Finish the Release -> 4.3 Tag the local Docker Image

fix(community): remove repeat step in 'community-5-release-guide'

---

docs/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/gateway-property-config.md

[DOC] gateway-property-config: add netty config

---

community/14-integration-test.md
i18n/zh/docusaurus-plugin-content-docs-community/current/14-integration-test.md

See [shenyu:#2559](https://github.com/apache/incubator-shenyu/pull/2559)

Simplify the integration test guide

---

docs/user-guide/http-proxy.md
docs/user-guide/spring-cloud-proxy.md

[Doc]: user guide support new feature  docs[http, spring-cloud]

---

docs/quick-start/quick-start-http.md
docs/user-guide/http-proxy.md
docs/user-guide/spring-cloud-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/quick-start/quick-start-http.md
i18n/zh/docusaurus-plugin-content-docs/current/quick-start/quick-start-springcloud.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/spring-cloud-proxy.md

about pr:
- https://github.com/apache/incubator-shenyu-website/pull/431
- https://github.com/apache/incubator-shenyu-website/pull/427
work list:

[doc]: add chinese docs[http,spring-cloud]

---

docs/deployment/deployment-custom.md
docs/deployment/deployment-docker.md
docs/deployment/deployment-k8s.md
docs/deployment/deployment-package.md
docs/deployment/deployment-quick.md
docs/user-guide/observability/tracing.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/observability/tracing.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-k8s.md
versioned_docs/version-2.4.0/deployment/deployment-custom.md
versioned_docs/version-2.4.0/deployment/deployment-docker.md
versioned_docs/version-2.4.0/deployment/deployment-k8s.md
versioned_docs/version-2.4.1/deployment/deployment-custom.md
versioned_docs/version-2.4.1/deployment/deployment-docker.md
versioned_docs/version-2.4.1/deployment/deployment-k8s.md

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>

Unify the version number of the deployment document

---

community/1-code-suggestions.md
i18n/zh/docusaurus-plugin-content-docs-community/current/1-code-suggestions.md

fix issue 458 add suggestions

---

event/2.4.2-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.4.2-release.md

[ISSUE #467] Add Chinese version introduction

---

docs/plugin-center/fault-tolerance/hystrix-plugin.md
docs/plugin-center/fault-tolerance/rate-limiter-plugin.md
docs/plugin-center/fault-tolerance/sentinel-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/fault-tolerance/hystrix-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/fault-tolerance/resilience4j-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/fault-tolerance/sentinel-plugin.md

This pr mainly does the following tasks
1. Remove duplicate parameters in hystrix plugin
2. Unify the description format in the plugin documentation

[DOC] Optimize the description of plugin documentation

---

docs/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/current/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.0/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.1/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.2/quick-start/quick-start-dubbo.md

see https://github.com/apache/incubator-shenyu/issues/3056

[apache/incubator-shenyu#3056] add dubbo note

---

i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-package.md

In Binary Packages Deployment,The description of MySQL stored data in Chinese documents is inconsistent with that in English documents.
Fixes #502

[ISSUE #502] In Binary Packages Deployment,The description of MySQL stored data in Chinese documents is inconsistent with that in English documents.

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

[ISSUE #509 ] fix shellcommand errors.

fix website:fix shellcommand error

---

docs/plugin-center/proxy/divide-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/proxy/divide-plugin.md

[ISSUE #507] add doc for retryStrategy in DividePlugin

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

[BUG] In the contributor-guide ,some links are faulty.
fixes #528  
FAQ  link   [../faq]
Committer link  [../committer]

[ISSUE #528] In the contributor-guide ,some links are faulty.

---

docs/plugin-center/observability/metrics-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/observability/metrics-plugin.md
static/img/shenyu/monitor/request_metric_dashboard.json

1. Let the datasource of grafana dashboard not bind uid.
2. Fix the legen error as shown in the image below. (because it uses the wrong metrics, should be `shenyu_request_type_total`)

Optimize grafana dashboard and documentation

---

event/2.2.0-release.md
event/2.3.0-release.md
event/2.4.0-release.md
event/2.4.1-release.md

[DOC] Edit order event

---

community/7-icla.md
i18n/zh/docusaurus-plugin-content-docs-community/current/7-icla.md

[ISSUE #545] add addressee and template

---

i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/http-process/redirect-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/http-process/request-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/http-process/rewrite-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/http-process/redirect-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/http-process/request-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/http-process/rewrite-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/plugin-center/http-process/redirect-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/plugin-center/http-process/request-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/plugin-center/http-process/rewrite-plugin.md

Polish the document
https://github.com/apache/incubator-shenyu/issues/3271
TASK_1

[ISSUE #3271] Polish the document Modify file content（#541）

---

i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/observability/metrics-plugin.md

> task: Translate the English expressions of the description column and help column in this document into Chinese, please make sure that your translation expresses the original English meaning as much as possible.

[ISSUE #3271][Task] translate descriptions

---

community/5-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/5-release-guide.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/developer/custom-parsing-ip-and-host.md

The docker image should support more platforms.This step needs to be done in the release
I've added new details to the release documentation based on the question mentioned in the [email](https://lists.apache.org/thread/xssr77v21f5v9roopn630yh4oykmnbrg)

update release docs

---

i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/developer/local-model.md

modify URL port from 9095 to 9195

modify URL port from 9095 to 9195

---

docusaurus.config.js

Enter https://shenyu.apache.org/
Now : 
After modified, it will become:

Modify tagline

---

.github/workflows/deploy.yml
docs/deployment/deployment-cluster.md
docs/deployment/deployment-package.md
docs/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-quick.md
versioned_docs/version-2.4.0/deployment/deployment-cluster.md
versioned_docs/version-2.4.0/deployment/deployment-package.md
versioned_docs/version-2.4.1/deployment/deployment-cluster.md
versioned_docs/version-2.4.1/deployment/deployment-package.md
versioned_docs/version-2.4.1/deployment/deployment-quick.md
versioned_docs/version-2.4.2/deployment/deployment-cluster.md
versioned_docs/version-2.4.2/deployment/deployment-package.md
versioned_docs/version-2.4.2/deployment/deployment-quick.md
versioned_docs/version-2.4.3/deployment/deployment-cluster.md
versioned_docs/version-2.4.3/deployment/deployment-package.md
versioned_docs/version-2.4.3/deployment/deployment-quick.md

[type:optimize] add download url for document.

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>

Add subsequent pull request submission guide

---

community/0-team.md
i18n/zh/docusaurus-plugin-content-docs-community/current/0-team.md

add github ids for new committers.

add github id for new committers in team page

---

docs/user-guide/register-center-instance.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/register-center-instance.md

Add consul support instructions to the register center instance document

Update register-center-instance doc

---

docs/deployment/deployment-docker.md
docs/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md

Deployment document description for updating MySQL version to 8.0.29

Update deployment mysql doc

---

community/3-contributor.md
i18n/zh/docusaurus-plugin-content-docs-community/current/3-contributor.md

tell people how to unsubscribe mail

tell people how to unsubscribe mail

---

versioned_docs/version-2.4.0/deployment/deployment-k8s.md
versioned_docs/version-2.4.1/deployment/deployment-k8s.md
versioned_docs/version-2.4.2/deployment/deployment-k8s.md
versioned_docs/version-2.4.3/deployment/deployment-k8s.md

https://github.com/apache/incubator-shenyu-website/issues/439
Solve an issue I raised myself

add: Modify the wrong configmap format

---

docs/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-k8s.md

ISSUE #439
first PR: #635 
Fix the remaining files.

doc deployment: Modify the k8s deployment files wrong configmap format

---

i18n/zh/docusaurus-plugin-content-docs/current/user-guide/register-center-access.md

[type:feat] add shenyu.register.enabled

[type:feat] add shenyu.register.enabled

---

.github/scripts/conf.py
docs/index.md
i18n/zh/docusaurus-plugin-content-docs/current/index.md

https://github.com/apache/shenyu-website/runs/7375254966?check_suite_focus=true
```
! LaTeX Error: Cannot determine size of graphic in /home/runner/work/incubator-
shenyu-website/incubator-shenyu-website/_build/doctrees/images/7a7994624a7c3eb8
7545710073f3557943595d9d/incubator-shenyu.svg (no BoundingBox).
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...                                              
l.350 ...073f3557943595d9d/incubator-shenyu}.svg}}
? 
! Emergency stop.
...                                              
l.350 ...073f3557943595d9d/incubator-shenyu}.svg}}
```

fix pdf generator error

---

docs/user-guide/property-config/admin-property-config.md
docs/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/admin-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/gateway-property-config.md

About #674
About apidoc in admin-property-config.yaml needs to be deleted. I have confirmed with Junwei about this.

[ISSUE #674] Optimize shenyu configuration document.

---

docs/quick-start/quick-start-websocket.md
i18n/zh/docusaurus-plugin-content-docs/current/quick-start/quick-start-websocket.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/quick-start/quick-start-websocket.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/quick-start/quick-start-websocket.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/quick-start/quick-start-websocket.md
versioned_docs/version-2.4.1/quick-start/quick-start-websocket.md
versioned_docs/version-2.4.2/quick-start/quick-start-websocket.md
versioned_docs/version-2.4.3/quick-start/quick-start-websocket.md

[ISSUE #675] Add quick start with websocket.

---

docs/user-guide/motan-proxy.md
docs/user-guide/tars-proxy.md
docs/user-guide/websocket-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/websocket-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/websocket-proxy.md
versioned_docs/version-2.4.0/user-guide/motan-proxy.md
versioned_docs/version-2.4.0/user-guide/tars-proxy.md
versioned_docs/version-2.4.1/user-guide/motan-proxy.md
versioned_docs/version-2.4.1/user-guide/tars-proxy.md
versioned_docs/version-2.4.2/user-guide/motan-proxy.md
versioned_docs/version-2.4.2/user-guide/tars-proxy.md
versioned_docs/version-2.4.3/user-guide/motan-proxy.md
versioned_docs/version-2.4.3/user-guide/tars-proxy.md
versioned_docs/version-2.4.3/user-guide/websocket-proxy.md

[ISSUE #716] Fix user-guide configuration error.

---

docs/user-guide/grpc-proxy.md
docs/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/http-proxy.md
versioned_docs/version-2.4.0/user-guide/grpc-proxy.md
versioned_docs/version-2.4.0/user-guide/http-proxy.md
versioned_docs/version-2.4.1/user-guide/grpc-proxy.md
versioned_docs/version-2.4.1/user-guide/http-proxy.md
versioned_docs/version-2.4.2/user-guide/grpc-proxy.md
versioned_docs/version-2.4.2/user-guide/http-proxy.md
versioned_docs/version-2.4.3/user-guide/grpc-proxy.md
versioned_docs/version-2.4.3/user-guide/http-proxy.md
versioned_docs/version-2.5.0/user-guide/grpc-proxy.md
versioned_docs/version-2.5.0/user-guide/http-proxy.md

About #716 , grpc and http proxy.

[ISSUE 716] Fix user-guide configuration error.

---

docs/deployment/deployment-docker.md
docs/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-package.md
versioned_docs/version-2.5.0/deployment/deployment-package.md

About https://github.com/apache/shenyu/issues/3928

Modify deployment document

---

docs/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-k8s.md
versioned_docs/version-2.4.2/deployment/deployment-k8s.md
versioned_docs/version-2.4.3/deployment/deployment-k8s.md
versioned_docs/version-2.5.0/deployment/deployment-k8s.md

[doc: k8s deployment] update the documentation

---

docs/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-k8s.md
versioned_docs/version-2.4.0/deployment/deployment-k8s.md
versioned_docs/version-2.4.1/deployment/deployment-k8s.md
versioned_docs/version-2.4.2/deployment/deployment-k8s.md
versioned_docs/version-2.4.3/deployment/deployment-k8s.md
versioned_docs/version-2.5.0/deployment/deployment-k8s.md

[fix: K8s deployment] fix K8s term

---

i18n/zh/docusaurus-plugin-content-docs/current/user-guide/spring-cloud-proxy.md

[doc: style] Update spring-cloud-proxy.md

---

community/14-client-sdk-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/14-client-sdk-release-guide.md

* Add client sdk release guide md.

[type: feature]  Add client sdk release guide md. 

---

community/14-shenyu-client-golang-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/14-shenyu-client-golang-release-guide.md

* fix golang client release guide title

[type:fix] fix golang client release guide title. (#765)

---

i18n/zh/docusaurus-plugin-content-docs-shenyuClientGolang/current/consul.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientGolang/current/etcd.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientGolang/current/nacos.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientGolang/current/zookeeper.md
shenyuClientGolang/consul.md
shenyuClientGolang/etcd.md
shenyuClientGolang/nacos.md
shenyuClientGolang/zookeeper.md

* Add remain client Golang docs

[type:feat] Add remain client Golang docs (#764)

---

src/components/Features.tsx

fix console error below when run dev

[type:fix] fix Features map each not has unique key prop error

---

docs/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-docker.md
versioned_docs/version-2.4.2/deployment/deployment-docker.md
versioned_docs/version-2.4.3/deployment/deployment-docker.md
versioned_docs/version-2.5.0/deployment/deployment-docker.md

fix: missing `--net shenyu` in docker deployment

---

docs/deployment/deployment-helm.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker-compose.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-helm.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-local.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-docker-compose.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-helm.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-local.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/deployment/deployment-quick.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-custom.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-docker-compose.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-helm.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-local.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-package.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/deployment/deployment-quick.md
versioned_docs/version-2.5.0/deployment/deployment-helm.md

[DOC] add helm deployment doc

---

community/15-shenyu-client-dotnet-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/15-shenyu-client-dotnet-release-guide.md

Added both Chinese and English .NET release guidances.

[ISSUE #785] add dotent client release guidance

---

community/15-shenyu-client-dotnet-release-guide.md
docusaurus.config.js
i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-docs-shenyuClientDotnet/current/consul.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientDotnet/current/etcd.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientDotnet/current/http.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientDotnet/current/nacos.md
i18n/zh/docusaurus-plugin-content-docs-shenyuClientDotnet/current/zookeeper.md
shenyuClientDotnet/consul.md
shenyuClientDotnet/etcd.md
shenyuClientDotnet/http.md
shenyuClientDotnet/nacos.md
shenyuClientDotnet/zookeeper.md
src/data/docsInfo.js

For #787 , added documents for ShenYu .NET client for both English and Chinese.

[ISSUE #787] add doc for dotnet client

---

community/15-shenyu-client-dotnet-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/15-shenyu-client-dotnet-release-guide.md
shenyuClientDotnet/consul.md
shenyuClientDotnet/etcd.md
shenyuClientDotnet/http.md
shenyuClientDotnet/nacos.md
shenyuClientDotnet/zookeeper.md

fix mistakes in dotnet client docs

[ISSUE #789] fix mistakes in dotnet client docs

---

community/14-shenyu-client-golang-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/14-shenyu-client-golang-release-guide.md

* fix golang client release doc. (#794)

[type:fix] fix golang client release doc. (#794)

---

docs/deployment/deployment-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-docker.md

fix docker deployment docs #776

fix docker deployment docs

---

community/14-shenyu-client-golang-release-guide.md
event/2.2.0-release.md
event/2.3.0-release.md
event/2.4.0-release.md
event/2.4.1-release.md
event/2.4.2-release.md
event/2.4.3-release.md
event/2.5.0-release.md
event/client-golang-1.0.0-release.md
i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-docs-event/current/client-golang-1.0.0-release.md
src/data/event.js

* add shenyu client golang release event

[type: feature] add shenyu client golang release event (#804)

---

event/2.2.0-release.md
event/2.3.0-release.md
event/2.4.0-release.md
event/2.4.1-release.md
event/2.4.2-release.md
event/2.4.3-release.md
event/2.5.0-release.md
event/client-dotnet-1.0.0-release.md
event/client-golang-1.0.0-release.md
i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-docs-event/current/2.2.0-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.3.0-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.4.0-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.4.1-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.4.2-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.4.3-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/2.5.0-release.md
i18n/zh/docusaurus-plugin-content-docs-event/current/client-dotnet-1.0.0-release.md
src/data/event.js

[DOC] add event doc for .NET client

---

i18n/zh/code.json
shenyuClientDotnet/consul.md
shenyuClientDotnet/etcd.md
shenyuClientDotnet/http.md
shenyuClientDotnet/nacos.md
shenyuClientDotnet/zookeeper.md
src/components/DownloadCompoent.module.css
src/components/DownloadCompoent.tsx

Add download docs for dotnet and golang client.
Seems my formatter auto formatted some files. :p
a snapshot

[DOC] Add docs about download for dotnet and golang client

---

docs/plugin-center/security/sign-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/security/sign-plugin.md

https://github.com/apache/shenyu/pull/4089 [BUG #4080]fix bug When using post requests, you can add parameters after the ur… #4089

adapt the sign plugin modify 

---

community/14-shenyu-client-golang-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/14-shenyu-client-golang-release-guide.md

[type:fix adjust release doc.]

---

community/16-shenyu-nginx-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/16-shenyu-nginx-release-guide.md
shenyuNginx/index.md

add shenyu nginx release guide

[DOC]add shenyu nginx release guide

---

community/16-shenyu-nginx-release-guide.md
event/nginx-1.0.0-1-release.md
i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-docs-community/current/16-shenyu-nginx-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-event/current/nginx-1.0.0-1-release.md
shenyuNginx/index.md
src/components/DownloadCompoent.tsx
src/data/event.js

[DOC]Add shenyu nginx download

---

helm/index.md
i18n/zh/docusaurus-plugin-content-docs-helm/current/index.md

Signed-off-by: Bird <aflybird0@gmail.com>

[DOC] update helm deployment doc for Oracle support

---

versioned_docs/version-2.5.0/design/register-center-design.md

[DOC]Outdated class name.

---

blog/DataSync-SourceCode-Analysis-Http-Data-Sync.md
i18n/zh/docusaurus-plugin-content-blog/DataSync-SourceCode-Analysis-Http-Data-Sync.md

feat: upgrade both Chinese and English blog to v2.5.0

[type: feat]: Upgrade DataSync-SourceCode-Analysis-Http-Data-Sync to v2.5.0

---

docs/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/plugin-center/rpc-proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.0/plugin-center/rpc-proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.1/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.2/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.3/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.5.0/plugin-center/proxy/spring-cloud-plugin.md

[DOC] modify spring-cloud-plugin assignment ribbon value to true

[DOC] modify spring-cloud-plugin assignment ribbon value to true

---

helm/index.md

about https://github.com/apache/shenyu-helm-chart/issues/24

[TASK] add doc ingress and hpa in helm.

---

versioned_docs/version-2.5.0/design/database-design.md

fix typo database-design.md

---

docs/index.md
i18n/zh/docusaurus-plugin-content-docs/current/index.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/index.md
versioned_docs/version-2.5.0/index.md

Signed-off-by: Bird <aflybird0@gmail.com>
1. remove duplicated `docker network create ...` command
2. remove unnecessary `>` prefix of every command

docs: update docker commands in index.md

---

docs/developer/custom-jwt-covert-algorithm.md
docs/plugin-center/security/jwt-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/developer/custom-jwt-covert-algorithm.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/security/jwt-plugin.md

About  apache/shenyu#3011 and apache/shenyu#4133

[doc: jwt plugin] update documentation of Jwt plugin

---

docs/plugin-center/mock/mock-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/mock/mock-plugin.md

About: apache/shenyu#4180、apache/shenyu#4236、 apache/shenyu#4256

[doc: mock plugin] update documentation of mock plugin

---

docs/quick-start/quick-start-dubbo.md
docs/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-blog-news/Apache-ShenYu-release-milestone-version-2.4.0.md
i18n/zh/docusaurus-plugin-content-docs/current/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/quick-start/quick-start-dubbo.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/dubbo-proxy.md
news/Apache-ShenYu-release-milestone-version-2.4.0.md
versioned_docs/version-2.4.0/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.0/user-guide/dubbo-proxy.md
versioned_docs/version-2.4.1/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.1/user-guide/dubbo-proxy.md
versioned_docs/version-2.4.2/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.2/user-guide/dubbo-proxy.md
versioned_docs/version-2.4.3/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.3/user-guide/dubbo-proxy.md
versioned_docs/version-2.5.0/quick-start/quick-start-dubbo.md
versioned_docs/version-2.5.0/user-guide/dubbo-proxy.md

[DOC] modify  maven introduce dubbo plugin the correct jar package

[DOC] modify  maven introduce dubbo plugin the correct jar package

---

docs/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.0/plugin-center/rpc-proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/plugin-center/proxy/spring-cloud-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.0/plugin-center/rpc-proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.1/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.2/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.3/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.4.3/quick-start/quick-start-dubbo.md
versioned_docs/version-2.4.3/user-guide/dubbo-proxy.md
versioned_docs/version-2.5.0/plugin-center/proxy/spring-cloud-plugin.md
versioned_docs/version-2.5.0/quick-start/quick-start-dubbo.md
versioned_docs/version-2.5.0/user-guide/dubbo-proxy.md

[DOC] modify  maven introduce alibaba dubbo plugin the correct jar package

[DOC] modify  maven introduce alibaba dubbo plugin the correct jar package

---

docs/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/current/deployment/deployment-k8s.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/deployment/deployment-k8s.md
versioned_docs/version-2.5.1/deployment/deployment-k8s.md

[doc: k8s deploy] update the doc of k8s deploy

---

versioned_docs/version-2.5.1/plugin-center/proxy/mqtt-plugin.md

Chinese and English documents are unified.

Improve the MQTT documentation

---

docs/quick-start/quick-start-springcloud.md

Fix a mistake in /docs/quick-start/quick-start-springcloud.md

[ISSUE #874] Fix a doc mistake

---

i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/register-center-access.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/property-config/register-center-access.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/user-guide/property-config/register-center-access.md

[ISSUE #876] Inconsistent of register-center-access

---

docs/plugin-center/http-process/redirect-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/plugin-center/http-process/redirect-plugin.md

Modify the image path
- modify the image path so that it can be displayed correctly.
#678 
#877

[Fix] modify the image path

---

helm/index.md
i18n/zh/docusaurus-plugin-content-docs-helm/current/index.md

https://github.com/apache/shenyu-helm-chart

docs(helm): update docs to support shenyu-helm-chart v0.6.1

---

helm/index.md
i18n/zh/docusaurus-plugin-content-docs-helm/current/index.md

update shenyu app version supported by helm from 2.5.0 to 2.5.1

doc(helm): update default app version

---

blog/SPI-SourceCode-Analysis-SPI.md

Hi Team,
Just came across this blog SPI source code analysis where the author has done a excellent job in explaining shenyu's SPI module.
However when I first read it , the service provider interface explanation and few other paragraph felt little confusing . So I have corrected them and submitted it in this PR.
Hopefully this helps other new learners like me .
Kindly review it and let me know if it is ok to change it or not ?
Task List
Corrected SPI explanation as it was little confusing
Corrected few code examples
Corrected few grammar since it was little confusing
Thanks and regards,
Praveen G

[ISSUE #931]  Correcting the blog SPI source code analysis 

---

docs/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.1/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.5.0/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.5.1/user-guide/property-config/gateway-property-config.md

<docs #939>fix a spell mistake, and imprecise wording.

---

src/components/Footer.tsx

Update Footer copyright to 2023.

Update Footer copyright to 2023.

---

docusaurus.config.js
package.json

New support Click to enlarge the picture to improve the reading experience

New support Click to enlarge the picture

---

i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/property-config/register-center-instance.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-consul.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-etcd.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-nacos.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-zookeeper.md
versioned_docs/version-2.6.0/user-guide/property-config/register-center-instance.md
versioned_docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-consul.md
versioned_docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-etcd.md
versioned_docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-nacos.md
versioned_docs/version-2.6.0/user-guide/sdk-usage/shenyu-sdk-zookeeper.md

fix latest version dependency name

fix document

---

blog/E2eTest-Analysis.md
i18n/zh/docusaurus-plugin-content-blog/E2eTest-Analysis.md
src/data/blogInfo.js

Add new blog type

---

docs/user-guide/sdk-usage/shenyu-sdk-consul.md
docs/user-guide/sdk-usage/shenyu-sdk-etcd.md
docs/user-guide/sdk-usage/shenyu-sdk-eureka.md
docs/user-guide/sdk-usage/shenyu-sdk-feign.md
docs/user-guide/sdk-usage/shenyu-sdk-nacos.md
docs/user-guide/sdk-usage/shenyu-sdk-zookeeper.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/sdk-usage/shenyu-sdk-feign.md

Add shenyu-sdk-feign doc.

---

docs/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.2/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/user-guide/property-config/gateway-property-config.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.0/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.4.2/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.4.3/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.5.0/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.5.1/user-guide/property-config/gateway-property-config.md
versioned_docs/version-2.6.0/user-guide/property-config/gateway-property-config.md

Fix reactor-netty options default value error.

[Fix reactor-netty docs] fix reactor-netty options default value error.

---

i18n/zh/docusaurus-plugin-content-pages/team.mdx
src/pages/team.mdx

add team.mdx

---

src/pages/event.tsx

Event List New Support Click on title to jump to details page

---

src/components/DownloadCompoent.tsx

Fixed incorrect text references

---

shenyuNginx/index.md

Remove incorrectly added text

---

.devcontainer/devcontainer.json
.gitpod.yml
README.md

Support `Contribute with Gitpod`.

Support `Contribute with Gitpod`.

---

i18n/zh/docusaurus-plugin-content-blog-news/Apache-ShenYu-Committer-2024-08-08.md
i18n/zh/docusaurus-plugin-content-pages/team.mdx
news/Apache-ShenYu-Committer-2024-08-08.md
src/data/newsInfo.js
src/pages/team.mdx

add new committer`s info and news

News and Committer

---

i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/grpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/motan-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/sofa-rpc-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/spring-cloud-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/tars-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.1/user-guide/proxy/websocket-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/grpc-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/motan-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/sofa-rpc-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/spring-cloud-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/tars-proxy.md
versioned_docs/version-2.6.1/user-guide/proxy/websocket-proxy.md

fix "Quick start with xxx" link 404 under Proxy page

[type:fix] fix "Quick start with xxx" link 404 under Proxy page

---

community/18-shenyu-client-python-release-guide.md
community/19-shenyu-client-rust-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/18-shenyu-client-python-release-guide.md
i18n/zh/docusaurus-plugin-content-docs-community/current/19-shenyu-client-rust-release-guide.md

add python and rust client release note

[type:feat] add more client release note

---

i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-blog-news/Apache-ShenYu-release-version-2.7.0.md
news/Apache-ShenYu-release-version-2.7.0.md

[release] release 2.7.0 news

---

src/data/docsInfo.js

[type:bugfix] fix version link

---

docs/user-guide/admin-usage/namepsace.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/admin-usage/namepsace.md

Modify known errors in namespace doc

[type:fix]fix namespace doc 

---

blog/Start-SourceCode-Analysis-Start-Demo-for-Contributor.md
i18n/zh/docusaurus-plugin-content-blog/Start-SourceCode-Analysis-Start-Demo-for-Contributor.md

1. Correct the JDK version indication error in the documentation: The minimum required JDK version is 17, not 1.8.
2. Add the minimum version requirement for Maven.
3. Add the Git operation process for low - network - quality environments.

[type:bugfix]Supplementary Documentation

---

docs/developer/spi/custom-metrics-monitor.md
docs/plugin-center/security/sign-plugin.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/proxy/dubbo-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/user-guide/proxy/http-proxy.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/plugin-center/proxy/dubbo-plugin.md
versioned_docs/version-2.4.0/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.4.0/user-guide/proxy/dubbo-proxy.md
versioned_docs/version-2.4.1/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.4.1/user-guide/proxy/dubbo-proxy.md
versioned_docs/version-2.4.2/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.4.2/user-guide/proxy/dubbo-proxy.md
versioned_docs/version-2.4.3/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.4.3/user-guide/proxy/dubbo-proxy.md
versioned_docs/version-2.5.0/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.5.1/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.5.1/plugin-center/security/sign-plugin.md
versioned_docs/version-2.6.0/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.6.0/plugin-center/security/sign-plugin.md
versioned_docs/version-2.6.1/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.6.1/plugin-center/security/sign-plugin.md
versioned_docs/version-2.7.0/developer/spi/custom-metrics-monitor.md
versioned_docs/version-2.7.0/plugin-center/security/sign-plugin.md

Continue Fixes https://github.com/apache/shenyu-website/issues/1060
Fixed most of it, I want to wait for this to be merged, and scan it again to see.

[type:bugfix] fix deadlink

---

.github/workflows/deploy.yml

upgrade node version from v18 to v20

feat: upgrade node version from v18 to v20

---

i18n/zh/code.json

describe：zh add title highlight
effect：

feat: add title highlight

---

i18n/zh/code.json
i18n/zh/docusaurus-theme-classic/navbar.json
news/Apache-ShenYu-Committer-2022-08-04.md
src/data/blogInfo.js
src/data/newsInfo.js

Simplified Chinese multilingual supplement

feat: Simplified Chinese multilingual supplement

---

i18n/zh/docusaurus-plugin-content-docs/version-2.7.0.1/user-guide/sdk-usage/shenyu-sdk-eureka.md

style: fix md show style

---

i18n/zh/docusaurus-plugin-content-blog-news/Apache-ShenYu-release-version-2.7.0.2.md
news/Apache-ShenYu-release-version-2.7.0.2.md
src/data/newsInfo.js

Add new version content to the news

feat: Add new version content to the news
